spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://dpg-cu0d8ihopnds738o4370-a.oregon-postgres.render.com:5432/likeat_db

    username: likeat_db_user
    password: roUDzqhXp4v5Jg83O164n5t2jE2WaZLj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true

app:
  cors:
    allowed-origins: http://localhost:5173/
    #allowed-origins: https://likeat-frontend.onrender.com

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day